# Generated by Django 4.2.6 on 2023-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='haslo', max_length=32),
            preserve_default=False,
        ),
    ]
